### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Ai2473** [KgDW/MadCat-deobf-decomp-buildable#1]
### Build failing log:

C:\Users\admin\Downloads\MadCat-deobf-decomp-buildable-main\build\tmp\expandedArchives\forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-sources.jar_02a406fcd54199648f4ff031e61ddeea\net\minecraftforge\fml\common\patcher\ClassPatchManager.java:33: error: cannot find symbol
import java.util.jar.Pack200;
                    ^
  symbol:   class Pack200
  location: package java.util.jar
C:\Users\admin\Downloads\MadCat-deobf-decomp-buildable-main\build\tmp\expandedArchives\forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-sources.jar_02a406fcd54199648f4ff031e61ddeea\net\minecraftforge\fml\common\patcher\ClassPatchManager.java:189: error: cannot find symbol
                        Pack200.newUnpacker().unpack(binpatchesDecompressed, jos);
                        ^
  symbol:   variable Pack200
  location: class ClassPatchManager
C:\Users\admin\Downloads\MadCat-deobf-decomp-buildable-main\build\tmp\expandedArchives\forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-sources.jar_02a406fcd54199648f4ff031e61ddeea\net\minecraftforge\fml\common\patcher\ClassPatchManager.java:33: error: cannot find symbol
import java.util.jar.Pack200;
                    ^
  symbol:   class Pack200
  location: package java.util.jar
C:\Users\admin\Downloads\MadCat-deobf-decomp-buildable-main\build\tmp\expandedArchives\forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-sources.jar_02a406fcd54199648f4ff031e61ddeea\net\minecraftforge\fml\common\patcher\ClassPatchManager.java:189: error: cannot find symbol
                        Pack200.newUnpacker().unpack(binpatchesDecompressed, jos);
                        ^
  symbol:   variable Pack200
  location: class ClassPatchManager

**Comment by KgDW** [comment]
Try using jdk8
